import Header from '../components/Header'
import Footer from '../components/Footer'

function Terms() {
  return (
    <div className="min-h-screen bg-[#f3f1e7] text-[#101923]">
      <Header />

      <main className="px-5 pb-20 pt-[72px] sm:px-8">
        <article className="mx-auto max-w-[760px] py-16 sm:py-24">
          <p className="text-[11px] uppercase tracking-[0.18em] text-[#4e5659]">
            Legal
          </p>

          <h1 className="serif mt-4 text-[46px] leading-none tracking-[-0.04em] sm:text-[60px]">
            Terms of Service
          </h1>

          <p className="mt-5 text-[13px] text-[#656b6c]">
            Last updated: October 2026
          </p>

          <div className="mt-12 space-y-10 text-[14px] leading-7 text-[#3f474b]">
            <section>
              <h2 className="serif text-[25px] text-[#101923]">
                1. Using MyNameLab
              </h2>

              <p className="mt-3">
                MyNameLab provides naming suggestions to help users explore
                possible names for businesses, brands, projects, products and
                other creative uses.
              </p>
            </section>

            <section>
              <h2 className="serif text-[25px] text-[#101923]">
                2. Naming suggestions
              </h2>

              <p className="mt-3">
                Names generated by MyNameLab are suggestions only. Users are
                responsible for determining whether a name is available,
                appropriate and legally usable.
              </p>
            </section>

            <section>
              <h2 className="serif text-[25px] text-[#101923]">
                3. Intellectual property
              </h2>

              <p className="mt-3">
                A generated suggestion does not guarantee trademark
                availability, domain availability or exclusive rights to a
                name.
              </p>
            </section>

            <section>
              <h2 className="serif text-[25px] text-[#101923]">
                4. Changes
              </h2>

              <p className="mt-3">
                We may update these terms as MyNameLab develops. Continued use
                of the service after changes are published means you accept the
                updated terms.
              </p>
            </section>
          </div>
        </article>
      </main>

      <Footer />
    </div>
  )
}

export default Terms